<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.example.org" xmlns:ns0="http://TargetNamespace.com/ServiceName" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/ReadRepsonseAutomotrizSPS.xsd"/>
            <oracle-xsl-mapper:rootElement name="ReadReponseAutomotrizSPS" namespace="http://TargetNamespace.com/ServiceName"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/Schemas/AutomotrizSPSEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="SyncAutomotrizSPSResponseEBM" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SUN JUN 20 20:58:13 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Code"/>
  <xsl:param name="Message"/>
  <xsl:param name="TrackingID"/>
  <xsl:param name="InstanceID"/>
  <xsl:param name="Operation"/>
   <xsl:template match="/">
      <tns:SyncAutomotrizSPSResponseEBM>
         <tns:Response>
            <tns:Code>
               <xsl:value-of select="$Code"/>
            </tns:Code>
            <tns:Message>
               <xsl:value-of select="$Message"/>
            </tns:Message>
            <tns:Detail>
               <xsl:value-of select="/ns0:ReadReponseAutomotrizSPS/ns0:_shards/ns0:successful"/>
            </tns:Detail>
            <tns:TrackingID>
               <xsl:value-of select="$TrackingID"/>
            </tns:TrackingID>
            <tns:InstanceID>
               <xsl:value-of select="$InstanceID"/>
            </tns:InstanceID>
            <tns:Operation>
               <xsl:value-of select="$Operation"/>
            </tns:Operation>
         </tns:Response>
         <xsl:for-each select="/ns0:ReadReponseAutomotrizSPS/ns0:hits/ns0:hits/ns0:_source">
            <tns:AutomotrizSPSEBO>
               <tns:Usuario>
                  <xsl:value-of select="ns0:usuario"/>
               </tns:Usuario>
               <tns:DescripcionAutoparte>
                  <xsl:value-of select="ns0:descripcion_autoparte"/>
               </tns:DescripcionAutoparte>
               <tns:Descuento>
                  <xsl:value-of select="ns0:descuento"/>
               </tns:Descuento>
               <tns:Fecha>
                  <xsl:value-of select="ns0:fecha"/>
               </tns:Fecha>
            </tns:AutomotrizSPSEBO>
         </xsl:for-each>
      </tns:SyncAutomotrizSPSResponseEBM>
   </xsl:template>
</xsl:stylesheet>
