<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.example.org" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/Schemas/AutomotrizSPSEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="SyncAutomotrizSPSResponseEBM" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/Schemas/AutomotrizSPSEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessAutomotrizSPSResponseEBM" namespace="http://www.example.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SUN JUN 20 13:19:28 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:ProcessAutomotrizSPSResponseEBM>
         <ns0:Response>
            <ns0:Code>
               <xsl:value-of select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:Response/ns0:Code"/>
            </ns0:Code>
            <ns0:Message>
               <xsl:value-of select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:Response/ns0:Message"/>
            </ns0:Message>
            <ns0:Detail>
               <xsl:value-of select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:Response/ns0:Detail"/>
            </ns0:Detail>
            <ns0:TrackingID>
               <xsl:value-of select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:Response/ns0:TrackingID"/>
            </ns0:TrackingID>
            <ns0:InstanceID>
               <xsl:value-of select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:Response/ns0:InstanceID"/>
            </ns0:InstanceID>
            <ns0:Operation>
               <xsl:value-of select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:Response/ns0:Operation"/>
            </ns0:Operation>
         </ns0:Response>
         <xsl:for-each select="/ns0:SyncAutomotrizSPSResponseEBM/ns0:AutomotrizSPSEBO">
            <ns0:AutomotrizSPSEBO>
               <ns0:Usuario>
                  <xsl:value-of select="ns0:Usuario"/>
               </ns0:Usuario>
               <ns0:DescripcionAutoparte>
                  <xsl:value-of select="ns0:DescripcionAutoparte"/>
               </ns0:DescripcionAutoparte>
               <ns0:Descuento>
                  <xsl:value-of select="ns0:Descuento"/>
               </ns0:Descuento>
               <ns0:Fecha>
                  <xsl:value-of select="ns0:Fecha"/>
               </ns0:Fecha>
            </ns0:AutomotrizSPSEBO>
         </xsl:for-each>
      </ns0:ProcessAutomotrizSPSResponseEBM>
   </xsl:template>
</xsl:stylesheet>
